name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Every hour at 00 minutes
  workflow_dispatch:
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0  # Replace with the desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with the path to your requirements file, if applicable

      - name: Run script and commit changes
        run: |
          python main.py
          git config --global user.name "Mike4544"
          git config --global user.email "mihai.tira@yahoo.ro"
          git commit -am "Update README file"
          git push
